apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: keda-php-demo
  namespace: keda-demo
spec:
  hosts:
    - php-demo.local
  pathPrefixes:
    - /
  scaleTargetRef:
    name: keda-php-demo
    kind: Deployment
    apiVersion: apps/v1
    service: keda-php-demo
    port: 80
  replicas:
    min: 0
    max: 10
  scaledownPeriod: 30
  scalingMetric:
    requestRate:
      granularity: 2s
      targetValue: 5
      window: 1s